# Generated by Django 3.2.18 on 2023-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(null=True),
        ),
    ]
