# Generated by Django 3.2.18 on 2023-03-09 11:52

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230309_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
